// `geins serve` — a localhost HTTP/WS backend for the desktop (Tauri) shell.
//
// This is the SAME binary as the CLI, run headless. The Tauri app spawns it as a
// sidecar (`geins serve --port 0 --token <secret>`), reads the assigned port from
// stdout, then loads the bundled web shell pointing at this server.
//
// Security: bound to 127.0.0.1 only, and every request (except /health) must
// present the shared `--token` via `Authorization: Bearer <token>` or `?token=`.
// The token is generated by Tauri and never leaves the local machine — it stops
// other local processes from driving the API.
//
// All real work is delegated to the existing headless functions (login flow,
// copilot stream, subcommand runner) — this file only wires HTTP/WS to them.
import { homedir } from 'node:os';
import { login, verify, fetchUser, type AuthResponse } from '../auth/login.ts';
import { loadSession, saveSession, clearSession, parseJwtExp } from '../auth/session.ts';
import { chatStream } from '../commands/copilot.ts';
import { executeGeinsCommand } from '../commands/copilot.ts';
import { WEB_SHELL_HTML } from './web-shell.ts';
import { spawnPty, ptyAvailable, type PtyProcess } from './pty.ts';
import { selfInvocation } from '../runtime.ts';
import { VERSION } from '../version.ts';

interface ServeOptions {
  port: number;
  token: string;
  host: string;
  /** Desktop mode: a clean TUI exit (ctrl-c, /exit) exits this server too, which closes the app. */
  exitOnTtyEnd: boolean;
}

function parseServeArgs(args: string[]): ServeOptions {
  const get = (name: string): string | undefined => {
    const i = args.indexOf(`--${name}`);
    return i !== -1 ? args[i + 1] : undefined;
  };
  const port = Number(get('port') ?? process.env['GEINS_SERVE_PORT'] ?? '0');
  const token = get('token') ?? process.env['GEINS_SERVE_TOKEN'] ?? '';
  const host = get('host') ?? '127.0.0.1';
  return {
    port: Number.isFinite(port) ? port : 0,
    token,
    host,
    exitOnTtyEnd: args.includes('--exit-on-tty-end'),
  };
}

// Short-lived store for auth that's mid-flow (awaiting MFA code or account pick).
// Localhost + single user, so an in-memory map keyed by an opaque id is enough.
const pending = new Map<string, AuthResponse>();
let pendingSeq = 0;

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

// Per-connection WebSocket state, set at upgrade time.
type WsData =
  | { kind: 'copilot' }
  | { kind: 'tty'; cols: number; rows: number; pty?: PtyProcess; earlyInput: string[]; closed?: boolean };

/**
 * Spawn the real Ink TUI (this same binary, no args) in a PTY for one /tty
 * connection. Raw PTY bytes stream to the client as binary frames; the client
 * sends JSON text frames: {t:'i',d} input · {t:'r',cols,rows} resize.
 * The desktop shell renders this with xterm.js — the exact terminal experience.
 */
async function startTty(ws: Bun.ServerWebSocket<WsData>, exitOnTtyEnd: boolean): Promise<void> {
  const data = ws.data;
  if (data.kind !== 'tty') return;
  const env: Record<string, string> = {};
  for (const [k, v] of Object.entries(process.env)) if (v !== undefined) env[k] = v;
  env['TERM'] = 'xterm-256color';
  env['COLORTERM'] = 'truecolor';
  if (!env['LANG']) env['LANG'] = 'en_US.UTF-8'; // app launches (Finder) have no locale set
  const pty = await spawnPty({
    argv: selfInvocation(), // no args → the TUI
    cols: data.cols,
    rows: data.rows,
    cwd: homedir(),
    env,
    onData: (chunk) => { if (!data.closed) ws.send(chunk); },
    onExit: (exitCode) => {
      data.pty = undefined;
      // The user quit the TUI itself (ctrl-c, /exit) while the window was attached:
      // in desktop mode that means "quit the app" — exit; the Tauri host watches the
      // sidecar and closes the window when it dies. NOT taken when `closed` (the ws
      // dropped first — reload/reconnect — where WE killed the TUI via SIGHUP), and
      // not on crashes (nonzero exit keeps the relaunch screen so the user sees it).
      if (exitOnTtyEnd && !data.closed && exitCode === 0) process.exit(0);
      if (data.closed) return;
      ws.send(JSON.stringify({ t: 'exit', code: exitCode }));
      ws.close();
    },
  });
  if (!pty) {
    ws.send(JSON.stringify({ t: 'error', message: 'PTY not available on this platform' }));
    ws.close();
    return;
  }
  if (data.closed) { pty.kill(); return; }
  data.pty = pty;
  // Flush keystrokes that arrived while the TUI was spawning.
  for (const d of data.earlyInput.splice(0)) pty.write(d);
}

/** Finalize a successful auth: pick the account, fetch the user, persist the session. */
async function finalizeLogin(auth: AuthResponse, accountKey?: string) {
  const accounts = auth.accounts ?? [];
  // Multiple accounts and none chosen yet → ask the client to pick.
  if (accounts.length > 1 && !accountKey) {
    const id = `p${++pendingSeq}`;
    pending.set(id, auth);
    return { stage: 'account' as const, pendingId: id, accounts };
  }
  const chosen = accountKey
    ? accounts.find((a) => a.accountKey === accountKey)
    : accounts[0];
  const user = await fetchUser(auth.accessToken);
  const name = user.name || [user.firstName, user.lastName].filter(Boolean).join(' ') || 'Unknown';
  await saveSession({
    accessToken: auth.accessToken,
    refreshToken: auth.refreshToken,
    accountKey: chosen?.accountKey ?? '',
    accountName: chosen?.displayName ?? '',
    tokenExpires: parseJwtExp(auth.accessToken),
    user: { email: user.email ?? '', name, roles: user.roles ?? [] },
  });
  return { stage: 'done' as const };
}

/**
 * When run as a desktop sidecar (`--watch-parent`), self-exit if the parent
 * process dies. The OS reparents orphans to PID 1, so a PPID of 1 means our
 * launcher is gone — guarantees no orphaned server even on a hard kill that
 * skips the app's normal shutdown.
 *
 * No "already 1 at startup" early-return: if the launcher crashes during its
 * own startup (e.g. mid `did_finish_launching`), we may be orphaned before
 * this first runs — that case must ALSO exit, the first tick handles it.
 */
function watchParent(): void {
  const timer = setInterval(() => {
    if (process.ppid === 1) {
      clearInterval(timer);
      process.exit(0);
    }
  }, 1000);
  timer.unref?.();
}

export async function serveCommand(args: string[]): Promise<void> {
  const { port, token, host, exitOnTtyEnd } = parseServeArgs(args);
  if (args.includes('--watch-parent')) watchParent();

  const authorized = (req: Request): boolean => {
    if (!token) return true; // no token configured → open (dev convenience)
    const header = req.headers.get('Authorization');
    if (header === `Bearer ${token}`) return true;
    const url = new URL(req.url);
    return url.searchParams.get('token') === token;
  };

  const server = Bun.serve<WsData>({
    port,
    hostname: host,
    async fetch(req, srv) {
      const url = new URL(req.url);
      const path = url.pathname;

      if (path === '/health') return jsonResponse({ ok: true, version: VERSION, tty: await ptyAvailable() });

      // WebSocket upgrade for streaming copilot turns.
      if (path === '/copilot') {
        if (!authorized(req)) return new Response('Unauthorized', { status: 401 });
        if (srv.upgrade(req, { data: { kind: 'copilot' } satisfies WsData })) return undefined as unknown as Response;
        return new Response('Expected WebSocket', { status: 426 });
      }

      // WebSocket upgrade for the desktop terminal: the TUI over a PTY.
      if (path === '/tty') {
        if (!authorized(req)) return new Response('Unauthorized', { status: 401 });
        if (!(await ptyAvailable())) return jsonResponse({ error: 'tty not supported on this platform' }, 501);
        const cols = Number(url.searchParams.get('cols') ?? '80') || 80;
        const rows = Number(url.searchParams.get('rows') ?? '24') || 24;
        const data: WsData = { kind: 'tty', cols, rows, earlyInput: [] };
        if (srv.upgrade(req, { data })) return undefined as unknown as Response;
        return new Response('Expected WebSocket', { status: 426 });
      }

      // Static shell at root.
      if (path === '/' || path === '/index.html') {
        return new Response(WEB_SHELL_HTML, { headers: { 'Content-Type': 'text/html; charset=utf-8' } });
      }

      // Everything below requires the token.
      if (!authorized(req)) return jsonResponse({ error: 'unauthorized' }, 401);

      if (path === '/version') return jsonResponse({ version: VERSION });

      if (path === '/session') {
        const session = await loadSession();
        if (!session) return jsonResponse({ loggedIn: false });
        return jsonResponse({
          loggedIn: true,
          user: session.user,
          accountKey: session.accountKey,
          accountName: session.accountName,
        });
      }

      if (path === '/logout' && req.method === 'POST') {
        await clearSession();
        return jsonResponse({ ok: true });
      }

      if (path === '/login' && req.method === 'POST') {
        const { username, password, accountKey } = (await req.json()) as {
          username?: string; password?: string; accountKey?: string;
        };
        if (!username || !password) return jsonResponse({ error: 'username and password required' }, 400);
        try {
          const auth = await login(username, password);
          if (auth.mfaRequired && auth.loginToken) {
            return jsonResponse({ stage: 'mfa', loginToken: auth.loginToken, mfaMethod: auth.mfaMethod });
          }
          return jsonResponse(await finalizeLogin(auth, accountKey));
        } catch (err) {
          return jsonResponse({ error: String((err as Error).message ?? err) }, 401);
        }
      }

      if (path === '/login/verify' && req.method === 'POST') {
        const { loginToken, mfaCode, accountKey } = (await req.json()) as {
          loginToken?: string; mfaCode?: string; accountKey?: string;
        };
        if (!loginToken || !mfaCode) return jsonResponse({ error: 'loginToken and mfaCode required' }, 400);
        try {
          const auth = await verify(loginToken, mfaCode);
          return jsonResponse(await finalizeLogin(auth, accountKey));
        } catch (err) {
          return jsonResponse({ error: String((err as Error).message ?? err) }, 401);
        }
      }

      if (path === '/login/account' && req.method === 'POST') {
        const { pendingId, accountKey } = (await req.json()) as { pendingId?: string; accountKey?: string };
        const auth = pendingId ? pending.get(pendingId) : undefined;
        if (!auth || !accountKey) return jsonResponse({ error: 'invalid pending login' }, 400);
        pending.delete(pendingId!);
        try {
          return jsonResponse(await finalizeLogin(auth, accountKey));
        } catch (err) {
          return jsonResponse({ error: String((err as Error).message ?? err) }, 401);
        }
      }

      if (path === '/command' && req.method === 'POST') {
        const { command } = (await req.json()) as { command?: string };
        if (!command) return jsonResponse({ error: 'command required' }, 400);
        const result = await executeGeinsCommand(command);
        return jsonResponse(result);
      }

      return jsonResponse({ error: 'not found' }, 404);
    },
    websocket: {
      open(ws) {
        if (ws.data?.kind === 'tty') void startTty(ws, exitOnTtyEnd);
      },
      async message(ws, raw) {
        const data = ws.data;

        if (data?.kind === 'tty') {
          let msg: { t?: string; d?: string; cols?: number; rows?: number };
          try {
            msg = JSON.parse(String(raw));
          } catch {
            return;
          }
          if (msg.t === 'i' && typeof msg.d === 'string') {
            if (data.pty) data.pty.write(msg.d);
            else data.earlyInput.push(msg.d); // TUI still spawning
          } else if (msg.t === 'r' && msg.cols && msg.rows) {
            data.cols = msg.cols;
            data.rows = msg.rows;
            data.pty?.resize(msg.cols, msg.rows);
          }
          return;
        }

        let prompt = '';
        try {
          const msg = JSON.parse(String(raw)) as { prompt?: string };
          prompt = msg.prompt ?? '';
        } catch {
          ws.send(JSON.stringify({ kind: 'error', text: 'invalid message' }));
          return;
        }
        if (!prompt) return;
        try {
          await chatStream(
            prompt,
            (text) => ws.send(JSON.stringify({ kind: 'text', text })),
            (event) => ws.send(JSON.stringify(event)),
          );
          ws.send(JSON.stringify({ kind: 'done' }));
        } catch (err) {
          ws.send(JSON.stringify({ kind: 'error', text: String((err as Error).message ?? err) }));
        }
      },
      close(ws) {
        const data = ws.data;
        if (data?.kind === 'tty') {
          data.closed = true;
          data.pty?.kill(); // window gone → hang up the TUI
          data.pty = undefined;
        }
      },
    },
  });

  // The sidecar host (Tauri) parses this line to learn the assigned port.
  console.log(`GEINS_SERVE_READY port=${server.port} host=${host}`);

  // Keep the process alive until killed by the host.
  await new Promise<void>(() => {});
}
