// `geins serve` — a localhost HTTP/WS backend for the desktop (Tauri) shell.
//
// This is the SAME binary as the CLI, run headless. The Tauri app spawns it as a
// sidecar (`geins serve --port 0 --token <secret>`), reads the assigned port from
// stdout, then loads the bundled web shell pointing at this server.
//
// Security: bound to 127.0.0.1 only, and every request (except /health) must
// present the shared `--token` via `Authorization: Bearer <token>` or `?token=`.
// The token is generated by Tauri and never leaves the local machine — it stops
// other local processes from driving the API.
//
// All real work is delegated to the existing headless functions (login flow,
// copilot stream, subcommand runner) — this file only wires HTTP/WS to them.
import { login, verify, fetchUser, type AuthResponse } from '../auth/login.ts';
import { loadSession, saveSession, clearSession, parseJwtExp } from '../auth/session.ts';
import { chatStream } from '../commands/copilot.ts';
import { executeGeinsCommand } from '../commands/copilot.ts';
import { WEB_SHELL_HTML } from './web-shell.ts';
import { VERSION } from '../version.ts';

interface ServeOptions {
  port: number;
  token: string;
  host: string;
}

function parseServeArgs(args: string[]): ServeOptions {
  const get = (name: string): string | undefined => {
    const i = args.indexOf(`--${name}`);
    return i !== -1 ? args[i + 1] : undefined;
  };
  const port = Number(get('port') ?? process.env['GEINS_SERVE_PORT'] ?? '0');
  const token = get('token') ?? process.env['GEINS_SERVE_TOKEN'] ?? '';
  const host = get('host') ?? '127.0.0.1';
  return { port: Number.isFinite(port) ? port : 0, token, host };
}

// Short-lived store for auth that's mid-flow (awaiting MFA code or account pick).
// Localhost + single user, so an in-memory map keyed by an opaque id is enough.
const pending = new Map<string, AuthResponse>();
let pendingSeq = 0;

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

/** Finalize a successful auth: pick the account, fetch the user, persist the session. */
async function finalizeLogin(auth: AuthResponse, accountKey?: string) {
  const accounts = auth.accounts ?? [];
  // Multiple accounts and none chosen yet → ask the client to pick.
  if (accounts.length > 1 && !accountKey) {
    const id = `p${++pendingSeq}`;
    pending.set(id, auth);
    return { stage: 'account' as const, pendingId: id, accounts };
  }
  const chosen = accountKey
    ? accounts.find((a) => a.accountKey === accountKey)
    : accounts[0];
  const user = await fetchUser(auth.accessToken);
  const name = user.name || [user.firstName, user.lastName].filter(Boolean).join(' ') || 'Unknown';
  await saveSession({
    accessToken: auth.accessToken,
    refreshToken: auth.refreshToken,
    accountKey: chosen?.accountKey ?? '',
    accountName: chosen?.displayName ?? '',
    tokenExpires: parseJwtExp(auth.accessToken),
    user: { email: user.email ?? '', name, roles: user.roles ?? [] },
  });
  return { stage: 'done' as const };
}

export async function serveCommand(args: string[]): Promise<void> {
  const { port, token, host } = parseServeArgs(args);

  const authorized = (req: Request): boolean => {
    if (!token) return true; // no token configured → open (dev convenience)
    const header = req.headers.get('Authorization');
    if (header === `Bearer ${token}`) return true;
    const url = new URL(req.url);
    return url.searchParams.get('token') === token;
  };

  const server = Bun.serve({
    port,
    hostname: host,
    async fetch(req, srv) {
      const url = new URL(req.url);
      const path = url.pathname;

      if (path === '/health') return jsonResponse({ ok: true, version: VERSION });

      // WebSocket upgrade for streaming copilot turns.
      if (path === '/copilot') {
        if (!authorized(req)) return new Response('Unauthorized', { status: 401 });
        if (srv.upgrade(req)) return undefined as unknown as Response;
        return new Response('Expected WebSocket', { status: 426 });
      }

      // Static shell at root.
      if (path === '/' || path === '/index.html') {
        return new Response(WEB_SHELL_HTML, { headers: { 'Content-Type': 'text/html; charset=utf-8' } });
      }

      // Everything below requires the token.
      if (!authorized(req)) return jsonResponse({ error: 'unauthorized' }, 401);

      if (path === '/version') return jsonResponse({ version: VERSION });

      if (path === '/session') {
        const session = await loadSession();
        if (!session) return jsonResponse({ loggedIn: false });
        return jsonResponse({
          loggedIn: true,
          user: session.user,
          accountKey: session.accountKey,
          accountName: session.accountName,
        });
      }

      if (path === '/logout' && req.method === 'POST') {
        await clearSession();
        return jsonResponse({ ok: true });
      }

      if (path === '/login' && req.method === 'POST') {
        const { username, password, accountKey } = (await req.json()) as {
          username?: string; password?: string; accountKey?: string;
        };
        if (!username || !password) return jsonResponse({ error: 'username and password required' }, 400);
        try {
          const auth = await login(username, password);
          if (auth.mfaRequired && auth.loginToken) {
            return jsonResponse({ stage: 'mfa', loginToken: auth.loginToken, mfaMethod: auth.mfaMethod });
          }
          return jsonResponse(await finalizeLogin(auth, accountKey));
        } catch (err) {
          return jsonResponse({ error: String((err as Error).message ?? err) }, 401);
        }
      }

      if (path === '/login/verify' && req.method === 'POST') {
        const { loginToken, mfaCode, accountKey } = (await req.json()) as {
          loginToken?: string; mfaCode?: string; accountKey?: string;
        };
        if (!loginToken || !mfaCode) return jsonResponse({ error: 'loginToken and mfaCode required' }, 400);
        try {
          const auth = await verify(loginToken, mfaCode);
          return jsonResponse(await finalizeLogin(auth, accountKey));
        } catch (err) {
          return jsonResponse({ error: String((err as Error).message ?? err) }, 401);
        }
      }

      if (path === '/login/account' && req.method === 'POST') {
        const { pendingId, accountKey } = (await req.json()) as { pendingId?: string; accountKey?: string };
        const auth = pendingId ? pending.get(pendingId) : undefined;
        if (!auth || !accountKey) return jsonResponse({ error: 'invalid pending login' }, 400);
        pending.delete(pendingId!);
        try {
          return jsonResponse(await finalizeLogin(auth, accountKey));
        } catch (err) {
          return jsonResponse({ error: String((err as Error).message ?? err) }, 401);
        }
      }

      if (path === '/command' && req.method === 'POST') {
        const { command } = (await req.json()) as { command?: string };
        if (!command) return jsonResponse({ error: 'command required' }, 400);
        const result = await executeGeinsCommand(command);
        return jsonResponse(result);
      }

      return jsonResponse({ error: 'not found' }, 404);
    },
    websocket: {
      async message(ws, raw) {
        let prompt = '';
        try {
          const msg = JSON.parse(String(raw)) as { prompt?: string };
          prompt = msg.prompt ?? '';
        } catch {
          ws.send(JSON.stringify({ kind: 'error', text: 'invalid message' }));
          return;
        }
        if (!prompt) return;
        try {
          await chatStream(
            prompt,
            (text) => ws.send(JSON.stringify({ kind: 'text', text })),
            (event) => ws.send(JSON.stringify(event)),
          );
          ws.send(JSON.stringify({ kind: 'done' }));
        } catch (err) {
          ws.send(JSON.stringify({ kind: 'error', text: String((err as Error).message ?? err) }));
        }
      },
    },
  });

  // The sidecar host (Tauri) parses this line to learn the assigned port.
  console.log(`GEINS_SERVE_READY port=${server.port} host=${host}`);

  // Keep the process alive until killed by the host.
  await new Promise<void>(() => {});
}
