// Command help text — the single source of truth for `geins <cmd> help` output AND the
// command catalog injected into the in-CLI copilot's system prompt (see copilot.ts).
// Add or change a command's docs HERE only; both surfaces stay in sync.

export const PRODUCT_HELP = [
  'geins product — query the product catalog (Management API)',
  '',
  'Subcommands:',
  '  get <id> [--idtype <0-3>] [--json]        Show one product (id is the internal id by default)',
  '  create [flags | --file|--body|stdin]      Create a product (see "create" below)',
  '  update <id> [--idtype <0-3>] [--file|--body|stdin]   Partial update (PUT; merges supplied fields)',
  '  delete <id> [--idtype <0-3>]              Permanently delete a product (alias: remove). --idtype 1 = by article number',
  '  list [filters] [--json]                   Query products (alias: query); defaults to page 1',
  '  items <id> [--idtype <0-3>] [--json]      List a product\'s items (SKUs of one product)',
  '  items create <productId> [--article <s>] [--name <s>] [--gtin <ean>] [--weight <g>] [--external-id <s>] [--inactive] [--idtype <0-3>]   Create a SKU (a product holds NO stock until it has an item)',
  '  stock set <itemId> <count> [--type <0-2>] [--idtype <0-4>]   Set stock on an item. --type: 0 Available (default), 1 Oversellable, 2 Static; --idtype: 0 internal id (default), 1 article, 4 external',
  '  stock get <itemId> [<itemId>...]          Read stock for one or more items (internal item ids)',
  '  price lists [--json]                      List the account\'s price lists (id, market, currency)',
  '  price get <productId> [--idtype <0-4>]    Read a product\'s resolved selling prices (inc/ex VAT per list)',
  '  price set <productId> <price> --pricelist <id> [--currency <code>] [--staggered <qty>]   Set a selling price (run "price lists" for the id)',
  '  variants <id> [--idtype <0-3>] [--json]   Show the product\'s variant group (sibling products + dimensions)',
  '  variants create [flags | JSON]            Create a variant group from existing products',
  '  variants set <id> <Label=Value>...        Set/overwrite dimensions of a product already in a group',
  '  variants delete <groupId>                 Delete a whole variant group',
  '  variants labels [list|add <n>|remove <n>|rename <old> <new>]   Manage variant dimension labels',
  '  images <id> [--json]                      List a product\'s images',
  '  images add <id> <file|url> [--name <n>] [--primary] [--position <n>] [--add]   Upload an image (jpg/png/gif); keeps & prints the stored name. --add uses POST (add) instead of PUT (upsert)',
  '  images add-existing <id> <imageName>      Link an already-uploaded image to the product (no upload); imageName is the original file name (the basename of the source)',
  '  images delete <id> <imageName>            Remove an image',
  '  images set-primary <id> <imageName>       Make an image the primary one',
  '  images reorder <id> <imageName> <pos>     Change an image\'s position',
  '  brands [list|get <id>|create --name <n> [--external-id <id>] [--desc <code>:<text>]|update <id> ...|delete <id>]   Manage brands (create: --external-id defaults to a slug of the name)',
  '  categories [list|get <id>|create --name <code>:<text> [--parent <id>] [--desc <code>:<text>] [--hidden] [--active|--inactive]|update <id> ...]   Manage categories (create is ACTIVE by default; pass --inactive to opt out)',
  '  text <id> [--idtype <0-3>] [--json]       List a product\'s localized texts (Names/ShortTexts/LongTexts/TechTexts)',
  '  text set <id> <name|shorttext|longtext|techtext> <locale>:<text>...  [--idtype <0-3>]   Set/merge localized text (one locale, keeps the rest)',
  '  categories assign <productId> <categoryId> [--idtype <0-3>]     Assign a category to a product',
  '  categories set-main <productId> <categoryId> [--idtype <0-3>]   Make a category the product\'s main (writes CategoryIds with it first)',
  '  categories unassign <productId> <categoryId> [--idtype <0-3>]   Remove a category from a product (preserves main)',
  '  relation-types [list|get <id>|add <name> [--order <n>]|update <id> [--name <n>] [--order <n>]|delete <id>]   Manage relation types',
  '  relations <id> [--json]                   List a product\'s related products',
  '  relations link <id> <relationTypeId> <relatedId...>     Link related products',
  '  relations unlink <id> <relationTypeId> <relatedId...>   Unlink related products',
  '  parameters <id> [--idtype <0-3>] [--json]   List a product\'s parameter values',
  '  parameters get <id> <paramId>             Show one resolved parameter value',
  '  parameters set <id> <paramId> <value> [--desc <code>:<text>]   Assign/update a value',
  '  parameters remove <id> <paramId>          Remove a parameter assignment',
  '  parameters batch <update|replace|remove> [--file|--body|stdin]   Batch value writes (JSON)',
  '  parameters defs [get <id>|create --name <n> --group <id> --type <1-7>|update <id> ...]   Parameter definitions',
  '  parameters groups [get <id>|create --name <n> [--order <n>] [--param <id>...]|update <id> ...]   Parameter groups',
  '  parameters predefined [get <id>|add --param <pid> --name <n>|rename <id> <name>]   Predefined values',
  '',
  'parameters — a "parameter" (e.g. Material) is a definition that belongs to a group and',
  '  has a type (1-7); a product gets a parameter VALUE by assigning a string to a parameterId.',
  '  batch update = merge (keeps unlisted); batch replace = removes values not in the body.',
  '  batch update/replace body: { "values": [ { "ProductId", "ParameterId", "Value", "LocalizedDescriptions"? } ] }',
  '  batch remove body:         { "assignments": [ { "ProductId", "ParameterId" } ] }',
  '',
  'create — create a product (convenience flags, or a full JSON body):',
  '  --article <s>                 Article number',
  '  --name <code>:<text>          Localized name (repeatable, e.g. en:"My Product")',
  '  --active / --inactive         Set Active (default: API default)',
  '  --brand <id>                  BrandId',
  '  --supplier <id>               SupplierId',
  '  --price <n> --currency <c>    Purchase price + currency',
  '  --category <id>               CategoryId (repeatable)',
  '  --vat-id <id>                 VatId, a whole number (e.g. 1 = 25%). VAT is set by id, NOT by rate;',
  '                                a decimal rate like 0.25 is rejected by the API, so it is ignored here',
  '  --external-id <s>             ExternalId',
  '  --file <path> | --body <json> | stdin   Full Product.Models.Write.Product body',
  '  --json                        Output the created product as JSON',
  '',
  'update <id> — partial update; supply only the fields to change as JSON:',
  '  --file <path> | --body <json> | stdin   e.g. { "Active": false, "BrandId": 7, "VatId": 1 }',
  '  note: write VAT as "VatId" (an id), not "Vat" (the read-only resolved rate)',
  '',
  'delete <id> — permanently delete a product (alias: remove):',
  '  --idtype <0-3>                How <id> is read: 0 internal id (default), 1 article number',
  '',
  'variants create — group existing products as variants of each other:',
  '  --name <name>                 Optional group name',
  '  --label <name>                Declared dimension (repeatable); omit to derive from products',
  '  --product <id>:L=V,L=V        A product + its dimension values (repeatable)',
  '  --collapse                    Set CollapseInLists',
  '  --idtype <0-3>                Id type for all product ids (default 0=internal)',
  '  --file <path> | --body <json> | stdin   JSON body form',
  '  --json                        Output the structured result',
  '  Labels must be registered first (variants labels add <name>); the main product',
  '  cannot be set via the API. JSON shape:',
  '  { "name"?, "collapse"?, "idType"?, "labels"?: [..], "products": [ { "id", "dimensions": { "Color":"Red" } } ] }',
  '',
  'list / query filters (repeatable flags accumulate):',
  '  --brand <id>                 Brand id',
  '  --category <id>              Category id',
  '  --supplier <id>              Supplier id',
  '  --id <productId>             Product id',
  '  --article <articleNumber>    Article number',
  '  --updated-after <ISO8601>    Updated after a date (e.g. 2026-01-01T00:00:00Z)',
  '  --created-after <ISO8601>    Created after a date',
  '  --sellable                   Only sellable products',
  '  --in-stock                   Only in-stock products',
  '  --page <n>                   Page number (page size 1000)',
  '  --batch <id>                 BatchId from a prior page (required for page > 1)',
  '  --include <fields>           Child collections, comma-separated (default Names). "" = basic data only,',
  '                               null/omit = no product data. Valid: Names, ShortTexts, LongTexts, TechTexts,',
  '                               Items, Prices, Categories, Parameters, Variants, Markets, Images, Feeds, Urls,',
  '                               ShippingFees, RelatedProducts, DiscountCampaigns, LowestPrice',
  '  --json                       Raw JSON output',
  '',
  'Examples:',
  '  geins product get 10001 --json',
  '  geins product create --article TEST-001 --name en:"Test Product" --active',
  '  geins product update 10001 --body \'{"Active":false}\'',
  '  geins product items 10001',
  '  geins product variants 10001',
  '  geins product images 10001',
  '  geins product images add 10001 ./hero.jpg --primary',
  '  geins product images add 10001 https://example.com/img.png --name img.png',
  '  geins product images add-existing 10001 hero.jpg',
  '  geins product brands',
  '  geins product brands create --name Nike --external-id nike',
  '  geins product categories',
  '  geins product text 2807',
  '  geins product text set 2807 longtext sv:"Kopplingsplintar av transparent nylon."',
  '  geins product text set 2807 longtext en:"Connection terminals."   # adds en, keeps sv',
  '  geins product categories create --name en:Shoes --parent 1',
  '  geins product categories assign 10001 42',
  '  geins product relation-types add Accessories',
  '  geins product relations link 10001 1 10002 10003',
  '  geins product parameters 10001',
  '  geins product parameters set 10001 42 "100% Cotton"',
  '  geins product parameters defs create --name Material --group 3 --type 1',
  '  geins product variants labels add Color',
  '  geins product variants create --name Tee --label Color --product 1005:Color=Red --product 1010:Color=Blue',
  '  geins product list --brand 1 --in-stock',
  '  geins product list --page 2 --batch <BatchId> --json',
  '  geins product list --account prod-elproman   # pick a live-API account (headless)',
].join('\n');

export const ORDER_HELP = [
  'geins order — inspect and handle orders (Management API)',
  '',
  'Subcommands:',
  '  list [filters] [--json]                   Query orders (alias: query); defaults to page 1',
  '  get <idOrPublicId> [--include <fields>] [--json]   One order (UUID → fetched by public id)',
  '  count <email>                             Number of orders for a customer email',
  '  statuses                                  List the available order status codes',
  '  create [--file <path> | --body \'<json>\' | stdin]   Create (place) an order; returns the new id',
  '  validate [--file | --body | stdin]        Validate an order body before creating it',
  '  status <id> <status> [<txId> [<secondaryTxId>]]    Change order status',
  '  update <id> [--external-id <s>] [--parcel <s>] [--external-status <0|10|20|30|40>] [--return-parcel <s>] | [--body \'<json>\']   Partial update',
  '  cancel-row <orderId> <orderRowId>         Cancel a single order row',
  '  comment <id> <text> [--system]            Add a comment to an order',
  '  transaction <id> <transactionId>          Set the payment transaction id',
  '  set-paid <paymentDetailId>                Mark a payment detail as paid',
  '  delete <id>                               Delete an order',
  '',
  'list / query filters:',
  '  --status <csv>               Status codes, comma-separated (StatusList)',
  '  --email <email>              Customer email',
  '  --customer <id>              Customer id',
  '  --market <id>                Market id',
  '  --payment <name>             Payment method name',
  '  --external-status <0-40>     External order status (0|10|20|30|40)',
  '  --created-after / --created-before <ISO8601>',
  '  --updated-after / --updated-before <ISO8601>',
  '  --completed-after / --completed-before <ISO8601>',
  '  --include <fields>           Child collections, e.g. Rows,ShippingAddress',
  '  --page <n>                   Page number',
  '  --batch <id>                 BatchId from a prior page (required for page > 1)',
  '  --json                       Raw JSON output',
  '',
  'Examples:',
  '  geins order statuses',
  '  geins order list --status 2 --json',
  '  geins order get 100123 --include Rows,ShippingAddress',
  '  geins order get 7b2e... --json            # public id (UUID)',
  '  geins order count customer@example.com',
  '  geins order comment 100123 "Called customer" ',
  '  geins order status 100123 5',
  '  geins order update 100123 --external-id EXT-9 --parcel ABC123',
  '  cat order.json | geins order create',
].join('\n');

export const CAMPAIGN_HELP = [
  'geins campaign — manage discount campaigns (Management API, /API/Campaign/*)',
  '',
  'Subcommands:',
  '  list [--json]                             List campaigns (summary rows)',
  '  types [--json]                            List discount type ids (CampaignTypeId) for THIS account',
  '  get <id> [--json]                         One campaign in full (CampaignId is a GUID)',
  '  create [flags | --file|--body|stdin]      Create a campaign (see below)',
  '  (no update/delete yet — the API update is PUT full-replace: partial updates are NOT supported,',
  '   so you must GET the campaign, merge your change into the whole body, then PUT it back.)',
  '',
  'TWO WAYS TO CREATE:',
  '  1) Flag mode — promo-code campaigns ONLY (CampaignBaseType=code). Quick % or fixed-amount codes.',
  '  2) Full body — --file <path> | --body \'<json>\' | piped stdin. Sends a CampaignDetailItemBase',
  '     verbatim. This is the ONLY way to make cart/product campaigns, free shipping, X-for-Y deals,',
  '     minimum-purchase rules, product selections, customer targeting, landing pages, etc.',
  '',
  'create — promo-code flag mode:',
  '  --promocode <CODE>           Discount code (required in flag mode) → CampaignBaseType=code',
  '  --market <id>                MarketId (required; see `geins account markets`)',
  '  --percentage <n>             Percentage discount → CampaignTypeId 3 + PercentageValue',
  '  --amount <CUR>:<n>           Fixed amount per currency → CampaignTypeId 4 + Amounts; repeatable',
  '  --title <text> / --lang <c>  Localized title + language code (default lang: en)',
  '  --from <ISO8601>             ValidFrom (default: now)',
  '  --to <ISO8601>               ValidTo',
  '  --usage-limit <n>            UsageLimit (max total redemptions)',
  '  --once-per-customer          OncePerCustomer (one redemption per customer)',
  '  --priority <n>               Priority',
  '  --enabled / --disabled       Enabled state (default: enabled)',
  '  --only-discounted            Restrict to already-discounted products (UseSalePrice). OFF by default —',
  '                               a normal promo code applies to ALL products. (The API would otherwise',
  '                               default this ON; flag mode forces it off unless you pass this flag.)',
  '  --json                       Raw JSON output',
  '',
  'FULL BODY SCHEMA (CampaignDetailItemBase) — for --file/--body/stdin. Keys are PascalCase:',
  '  Identity & type:',
  '    CampaignBaseType  int    1=cart, 2=code, 3=product   (a "code" campaign REQUIRES PromoCode)',
  '    CampaignTypeId    int    the discount mechanic; built-ins 3=Percentage, 4=Fixed amount.',
  '                             Type ids are account-defined — confirm with `geins campaign types`.',
  '    MarketId          str    market id (required in practice)',
  '    PromoCode         str    the code (code-type campaigns)',
  '    Title             [{Language,Value}]   localized titles; HideTitle:bool to suppress display',
  '    Description       str',
  '    Enabled           bool   ;  Priority int  ;  Group str (groups related campaigns)',
  '  Discount value (set the one that matches CampaignTypeId):',
  '    PercentageValue   number      e.g. 10 = 10% off (percentage type)',
  '    Amounts           {CUR:number}  fixed discount per ISO currency, e.g. {"SEK":50,"EUR":5}',
  '    Prices            {CUR:number}  fixed target price per currency (price-type campaigns)',
  '    FreeShipping      bool',
  '    BuyQuantity / PayForQuantity  int   X-for-Y deals (e.g. buy 3, pay for 2)',
  '  Eligibility & limits:',
  '    ValidFrom / ValidTo            ISO8601 date-time active window',
  '    UsageLimit        int   max total redemptions  ;  OncePerCustomer bool',
  '    MinimumQuantity   int   min items in cart',
  '    MinimumPurchaseAmounts  {CUR:number}   min cart value per currency',
  '    CheckMinAmountAfterDiscounts  bool   ;  Scoped bool (apply minimums to selected products only)',
  '    SelectedUsers     [email]      target specific customers',
  '    SelectedGroups    [groupId]    target customer groups',
  '  Combination & sale handling:',
  '    StopCombining  bool  ;  CantCombineWithCartCampaign bool  ;  ExcludeProductsOnSale bool',
  '    UseSalePrice  bool  ← admin "Only include discounted products"; API DEFAULTS THIS TRUE. Send',
  '                          false for a normal store-wide discount (see PITFALLS).',
  '    SaleTypesToEnforce int (0=NOT_SET,1=campaign,2=sale,3=all)',
  '    PriceOutput  int (0=Campaign,1=Sale)',
  '  ProductSelection (cart/product campaigns — which products the campaign applies to):',
  '    { "Include": {…}, "Exclude": {…} }   OMIT entirely for code campaigns (do NOT send null)',
  '    Each Include/Exclude block:',
  '      Condition   int   0=AND, 1=OR  (how the criteria combine)',
  '      Categories  [{Id,Name}]   ;   Brands [{Id,Name}]   ;   Products [int]  (product ids)',
  '      Price       [{ "Condition":0=lt|1=gt|2=eq, "Prices":{CUR:number} }]',
  '  LandingPage (optional): { Title/Description:[{Language,Value}], Url, Meta }',
  '',
  'Examples:',
  '  geins campaign types --json                       # discover this account\'s CampaignTypeId values',
  '  geins campaign create --promocode SUMMER10 --percentage 10 --market 1 --title "Summer" --lang sv',
  '  geins campaign create --promocode FIX50 --amount SEK:50 --amount EUR:5 --market 1',
  '  # Cart campaign: 15% off a category, min 2 items. Put the body in a file, then:',
  '  geins campaign create --file campaign.json --json',
  '  # …where campaign.json contains:',
  '  #   {',
  '  #     "CampaignBaseType": 1, "CampaignTypeId": 3, "MarketId": "1",',
  '  #     "PercentageValue": 15, "MinimumQuantity": 2, "Enabled": true,',
  '  #     "Title": [{ "Language": "en", "Value": "Category deal" }],',
  '  #     "ProductSelection": { "Include": { "Condition": 0, "Categories": [{ "Id": 42, "Name": "" }] } }',
  '  #   }',
  '  cat campaign.json | geins campaign create --json     # or pipe it via stdin',
].join('\n');

export const ACCOUNT_HELP = [
  'geins account — show account settings (v2 Account API)',
  '',
  'Subcommands:',
  '  list [--json]           List the accounts you can access (● = current)',
  '  (none)                  Overview: markets + languages + locales',
  '  markets [--json]        List market definitions (country-currency, e.g. SE-SEK, with VAT)',
  '  languages [--json]      List the account\'s languages (code + name)',
  '  locales [--json]        List locales (language-country tags, e.g. sv-SE) derived from channels',
  '',
  'Target another account for a single command with --account-name <name> (resolves the',
  'friendly name to the x-account-key). For live-API commands (product/order), pick the apikey',
  'profile with --account <name>. The two are independent (different APIs).',
  '',
  'Examples:',
  '  geins account list',
  '  geins workflow list --account-name labs        # run against the "labs" v2 account',
  '  geins account markets --account-name demogeins --json',
  '  geins product get 10001 --account prod-labs    # live API, by apikey profile',
].join('\n');

export const MERCHANT_HELP = [
  'geins merchant — storefront data via the Merchant API (GraphQL)',
  '',
  'Shows what a customer sees: products for sale in a sales channel, carts, and checkout.',
  'Requires an api-key profile (geins apikey set ...) and a merchant context',
  '(geins merchant config set ...). Channel/market/locale resolve per field as:',
  'flag → GEINS_* env (GEINS_CHANNEL/GEINS_TLD/GEINS_MARKET/GEINS_LOCALE/GEINS_MERCHANT_ACCOUNT)',
  '→ value stored on the active profile.',
  '',
  'Products:',
  '  product search [text] [--category <alias>] [--brand <alias>] [--take N] [--skip N] [--json]',
  '  product <productId|term> [--json]      Full detail for one product',
  '',
  'Catalog:',
  '  categories [--json]                    List categories (id · name · alias)',
  '  brands [--json]                        List brands (id · name · alias)',
  '',
  'Cart:',
  '  cart create                            Create a cart, prints its id',
  '  cart get <id>                          Show a cart and its total',
  '  cart add <id> --sku <skuId> [--qty N]  Add an item',
  '  cart update <id> --item <itemId> --qty N   Change an item quantity',
  '  cart remove <id> --item <itemId>       Remove an item',
  '  cart promo <id> <code>                 Apply a promotion code',
  '',
  'Checkout:',
  '  token <cartId> [options]               Generate a checkout token from a cart',
  '    --url                                Print the full https://checkout.geins.services/<token> link',
  '    --payment <id> / --shipping <id>     Preselect a payment/shipping method',
  '    --available-payments <csv>           Restrict selectable payment method ids (e.g. 18,23)',
  '    --available-shipping <csv>           Restrict selectable shipping method ids',
  '    --customer-type person|organization  Customer type (default person)',
  '    --editable / --no-copy               Allow cart editing / do not copy the cart',
  '    --success/--cancel/--continue/--terms/--privacy <url>   Redirect URLs',
  '    --branding <json|@file>              Branding { title, icon, logo, styles:{...} }',
  '    --user <json|@file>                  Logged-in user object',
  '  token parse <token>                    Decode a token payload (debug, offline)',
  '',
  'Config (per api-key profile):',
  '  config                                 Show the resolved context + checkout defaults',
  '  config set [--channel <c>] [--tld <t>] [--market <m>] [--locale <l>]',
  '             [--store-account <slug>] [--environment prod|qa|dev]',
  '             [--success/--cancel/--continue/--terms/--privacy <url>]',
  '             [--default-payment <id>] [--default-shipping <id>]',
  '             [--customer-type person|organization] [--branding <json|@file>]',
  '             Persist context + default checkout settings baked into every token.',
  '',
  'The success URL automatically gets Geins params appended',
  '(?geins-cart={geins.cartid}&geins-pm=…&geins-pt=…&geins-uid=…) so your',
  'confirmation page receives the order. Redirect URLs/branding are stable per',
  'storefront — set them once with `config set`; per-token flags override.',
  '',
  'Examples:',
  '  geins merchant config set --channel 1 --tld se --market se --locale sv-SE --store-account labs',
  '  geins merchant config set --success https://shop.com/thanks --terms https://shop.com/terms',
  '  geins merchant product search shoe --take 5 --json',
  '  CART=$(geins merchant cart create)',
  '  geins merchant cart add $CART --sku 123 --qty 2',
  '  geins merchant token $CART --url',
].join('\n');

/**
 * Top-level command groups. This is the catalog the in-CLI copilot is given — one line
 * per group, NOT every flag. The copilot discovers exact subcommands/flags by running
 * `geins <group> help` (whose text is the *_HELP consts above). Add a new group here once;
 * never re-list its subcommands in the copilot prompt.
 */
export const MEMORY_HELP = [
  'geins memory — the copilot knowledge base for the active account (per apikey/session bucket).',
  '',
  '  list [--json]                 Show everything learned: entities, patterns, preferences, recent Q&A',
  '  add <category> "<fact>"       Persist a durable fact. category: project|workflow|api|preference|pattern',
  '  export [--json]               Write a Markdown (or JSON) snapshot into the output folder',
  '  clear                         Wipe the knowledge base for this account',
  '  on | off                      Turn copilot memory on/off (off = no recall, no persist, no prompt instructions)',
  '  status                        Show whether copilot memory is on or off',
  '',
  'Notes:',
  '- Stored in the global Synapse folder `~/.synapse` (override with $GEINS_SYNAPSE_DIR) — the single',
  '  memory shared by every model backend; legacy `~/.config/geins/memory` is migrated on first use.',
  '- Memory is account-scoped — switching apikey/account shows a different bucket. Buckets are Synapse',
  '  sub-folders named `<accountName>_<apikeyProfile>` (e.g. `launch5_prod-launch5`); the output folder',
  '  nests its files the same way.',
  '- The copilot writes here automatically: [MEMORY]category:fact[/MEMORY] tags and `geins memory add`',
  '  both land in `add`; each copilot turn also records the prompt + a one-line answer summary.',
  '- Full session transcripts (commands + copilot turns) live in the bucket\'s sessions/ folder —',
  '  list them with `geins resume`, read one with `geins resume <id>`; the copilot does the same',
  '  when asked to continue earlier work.',
  '- View it interactively with `/memory`; `/memory clear` also resets chat history + command context.',
].join('\n');

export const APIKEY_HELP = [
  'geins apikey — live-API credential profiles (one per account API User). The live',
  'Management/Merchant APIs are single-account, so each profile holds one API User\'s creds;',
  'one is active at a time and drives product/order/campaign/merchant commands.',
  '',
  '  set [flags]                   Add (or replace) a profile from its four credentials, validate, activate',
  '  list | status                 List profiles; ● marks the active one',
  '  use <name>                    Switch the active profile',
  '  remove <name>                 Delete one profile',
  '  clear                         Delete all profiles',
  '',
  'set — all four credentials in ONE command (no prompts):',
  '  geins apikey set \\',
  '    --username <u> \\            # API User username (e.g. "cli")',
  '    --mgmt-key <k> \\           # Management API Key — also the profile name (e.g. "prod-launch4")',
  '    --mgmt-password <p> \\      # Management API Password',
  '    --merchant-key <k>          # Merchant API Key (a GUID)',
  '',
  '  Each flag also reads from an env var if omitted: GEINS_API_USERNAME, GEINS_MGMT_API_KEY,',
  '  GEINS_MGMT_API_PASSWORD, GEINS_MERCHANT_API_KEY. The profile is keyed by the Management API Key.',
  '  set validates both APIs before saving — bad creds are rejected, nothing is stored.',
  '',
  'From a screenshot of the Geins admin "API User" page (Username, Management API Password,',
  'Management API Key, Merchant API Key — shown only once): read those four values off the image and',
  'pass them straight to `apikey set`. That page is the canonical source for these credentials.',
].join('\n');

export const COMMAND_GROUPS: ReadonlyArray<{ name: string; synopsis: string }> = [
  { name: 'whoami', synopsis: 'show the authenticated user + active account' },
  { name: 'account', synopsis: 'account settings: markets, languages, locales (v2 Account API)' },
  { name: 'product', synopsis: 'catalog: get/list/create/update/delete products, items (SKUs), stock, prices, variants, images, text, parameters, brands, categories, relations' },
  { name: 'order', synopsis: 'orders: list/get/count, status, update, comment, cancel-row, create' },
  { name: 'campaign', synopsis: 'discount campaigns: list/get/types/create — promo-code (% or fixed), or cart/product campaigns (free shipping, X-for-Y, min-purchase, product selection) via full JSON body' },
  { name: 'merchant', synopsis: 'storefront (Merchant API): product search, categories, brands, cart, checkout token' },
  { name: 'workflow', synopsis: 'orchestrator automations: list/get/create/update/run/logs/enable/disable/manifest/vars (only when the user asks for a workflow)' },
  { name: 'apikey', synopsis: 'manage API-key profiles (per-account credentials)' },
  { name: 'output', synopsis: 'set/show the folder where command JSON is dumped' },
  { name: 'memory', synopsis: 'copilot knowledge base: list/add/export/clear durable facts, preferences, and recent Q&A for this account; on/off to toggle memory' },
];

/**
 * Non-obvious API behaviours that make commands fail in surprising ways. Surfaced to the
 * copilot so it does not repeat the same 4xx/5xx. Keep each line concrete and command-oriented.
 */
export const PITFALLS = [
  'PITFALLS — Management API quirks that cause confusing errors. Read before writing:',
  '- When creating any resource that carries human-readable content (product name/text, category',
  '  name, brand, campaign name, etc.), first run `geins account languages` to see the account\'s',
  '  ACTIVE languages, and supply that content for EACH active language — not just one. A resource',
  '  created in a single language shows up blank in the other storefront locales.',
  '- VAT on product create/update is written as "VatId" (an integer id, e.g. 1 = 25%), NEVER as',
  '  "Vat" (the read-only resolved rate). Sending {"Vat":0.25} → 400 "could not parse body";',
  '  {"Vat":25} → 400 "Missing VatType". Use --vat-id <id>, or omit it to take the account default.',
  '- Brands need an ExternalId; `product brands create` auto-fills a slug of the name if you omit',
  '  --external-id (a raw POST with no ExternalId 500s "database error").',
  '- `product brands list` / categories Query return a BARE ARRAY, not an envelope — a count of 0',
  '  with data present usually means something read .Resource off an array; trust the rows.',
  '- The Category API defaults a new category to INACTIVE when "Active" is omitted (assignments to an',
  '  inactive category read back empty). `product categories create` now sends Active:true by default',
  '  (pass --inactive to opt out); if you build a Category body yourself, include "Active": true.',
  '- Main category = the FIRST id in CategoryIds on create/update (MainCategoryId is read-only).',
  '  Use `product categories set-main <productId> <categoryId>` to reorder it to the front.',
  '- Image upload: PUT (default) writes the exact name and overwrites; POST (`images add --add`)',
  '  auto-suffixes on collision (6438.jpg → 6438_1.jpg). Read the stored FileName back; do not assume it.',
  '- A freshly created product has NO items (SKUs) and therefore cannot hold stock. To give it stock:',
  '  `product items create <productId> --article <sku>` then `product stock set <itemId> <count>`.',
  '  Stock is per item, not per product; StockType 0 = Available (the warehouse count you normally set).',
  '- SELLING price ≠ purchase price. The product\'s `--price`/PurchasePrice is the supplier/cost price.',
  '  Customer-facing selling prices live in PRICE LISTS (market + currency scoped): set them with',
  '  `product price set <productId> <price> --pricelist <id>` (find the id via `product price lists`),',
  '  and read them with `product price get <productId>`. PUT /API/PriceList/Price is a bulk upsert —',
  '  its response carries UpdateCount plus Invalid/NotFound rows, so a 200 can still mean nothing changed.',
  '- Campaign discount mechanic is chosen by CampaignTypeId, not inferred: 3=Percentage needs',
  '  PercentageValue; 4=Fixed amount needs Amounts. Amounts/Prices/MinimumPurchaseAmounts are objects',
  '  KEYED BY ISO currency ({"SEK":50}), never bare numbers. Type ids are account-defined — run',
  '  `geins campaign types` first. CampaignBaseType=code (2) requires a PromoCode; cart=1/product=3 do not.',
  '- Campaign ProductSelection is only for cart/product campaigns. For a promo-code campaign OMIT it',
  '  entirely — do not send "ProductSelection":null (it is optional, not documented-nullable). Inside it,',
  '  Include/Exclude use Condition 0=AND/1=OR, and each Price rule uses Condition 0=lt/1=gt/2=eq.',
  '- Campaign "UseSalePrice" DEFAULTS TO TRUE on the API when omitted — this is the admin "Only include',
  '  discounted products" toggle, which silently restricts the campaign to already-discounted products.',
  '  A normal store-wide promo code must send "UseSalePrice": false explicitly. The flag-mode',
  '  `campaign create` already forces it off (pass --only-discounted to opt back in); when you build a',
  '  body yourself (--body/--file), always include "UseSalePrice": false unless the user asked to limit',
  '  the campaign to discounted products.',
  '- Campaign update via the API is a PUT FULL-REPLACE (partial updates unsupported): GET the campaign,',
  '  merge your change into the entire body, then PUT — sending a partial body wipes the omitted fields.',
  '- Always prefer --json for any output you need to parse; the default text output is for humans.',
].join('\n');

/** The command catalog block injected into the copilot system prompt: groups + how to drill in. */
export function buildCommandCatalog(): string {
  const groups = COMMAND_GROUPS.map((g) => `  geins ${g.name.padEnd(9)} — ${g.synopsis}`).join('\n');
  return [
    'COMMAND GROUPS (run `geins <group> help` for exact subcommands, flags, and examples before using one):',
    groups,
    '',
    'Discovery rules:',
    '- Do NOT guess subcommands or flags. If unsure of the exact syntax, FIRST run `geins <group> help`',
    '  (e.g. `geins product help`) and read it, then run the real command.',
    '- Add `--json` whenever you need to parse, filter, or transform the result.',
    '- `geins <group>` with no subcommand prints that group\'s help too.',
  ].join('\n');
}
