#!/usr/bin/env bun
/**
 * Compiles the CLI into a single standalone binary via `bun build --compile`.
 *
 * Two resolver plugins:
 *  - Ink lazily imports `react-devtools-core` (only used when DEV=true). That dep
 *    can't resolve inside the compiled binary, so it's aliased to a no-op stub.
 *  - `src/server/pty-assets.ts` (dev: loads node-pty's native files from
 *    node_modules) is swapped for a GENERATED module that embeds pty.node (+
 *    macOS spawn-helper) for the target platform and extracts them at runtime.
 *    Targets without matching native files on this machine (Windows, or a
 *    cross-compile without the foreign prebuild) get a stub — `geins serve`
 *    then reports tty:false and the desktop shell falls back to the HTML REPL.
 *
 * Usage:
 *   bun run scripts/build-cli.ts                       # host platform → dist/geins
 *   bun run scripts/build-cli.ts --target bun-linux-x64 --outfile dist/geins-linux-x64
 */
import { resolve, join } from 'node:path';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

const ROOT = resolve(import.meta.dir, '..');
const STUB = resolve(import.meta.dir, 'stubs/react-devtools-core.ts');
const PTY_ASSETS_SRC = resolve(ROOT, 'src/server/pty-assets.ts');

function flag(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 ? process.argv[i + 1] : undefined;
}

const outfile = flag('outfile') ?? 'dist/geins';
const target = flag('target'); // e.g. bun-darwin-arm64, bun-linux-x64, bun-windows-x64

/** node-pty native file locations per bun compile target. */
function ptyNativeFiles(bunTarget: string): { pty: string; helper?: string } | null {
  const pkg = resolve(ROOT, 'node_modules/node-pty');
  const prebuild = (dir: string) => ({
    pty: join(pkg, 'prebuilds', dir, 'pty.node'),
    helper: join(pkg, 'prebuilds', dir, 'spawn-helper'),
  });
  switch (bunTarget) {
    case 'bun-darwin-arm64': return prebuild('darwin-arm64');
    case 'bun-darwin-x64': return prebuild('darwin-x64');
    // No shipped Linux prebuild — node-gyp builds it on install (trustedDependencies).
    case 'bun-linux-x64':
    case 'bun-linux-arm64': return { pty: join(pkg, 'build', 'Release', 'pty.node') };
    default: return null; // windows: conpty not wired up yet
  }
}

function hostBunTarget(): string {
  const plat = process.platform === 'darwin' ? 'darwin' : process.platform === 'win32' ? 'windows' : 'linux';
  const arch = process.arch === 'arm64' ? 'arm64' : 'x64';
  return `bun-${plat}-${arch}`;
}

/** Write the generated pty-assets replacement module and return its path. */
function generatePtyAssetsModule(bunTarget: string): string {
  const dir = resolve(ROOT, 'node_modules/.geins-build');
  mkdirSync(dir, { recursive: true });
  const out = join(dir, `pty-assets.${bunTarget}.ts`);
  const extract = resolve(ROOT, 'src/server/pty-extract.ts');

  const files = ptyNativeFiles(bunTarget);
  const missing = files && (!existsSync(files.pty) || (files.helper !== undefined && !existsSync(files.helper)));
  if (!files || missing) {
    if (missing) {
      console.warn(`⚠ node-pty native files for ${bunTarget} not found locally — building without /tty support`);
    }
    writeFileSync(out, [
      `// GENERATED by scripts/build-cli.ts — no PTY support for ${bunTarget}.`,
      `export type { PtyAssets } from ${JSON.stringify(extract)};`,
      `export async function resolvePtyAssets() { return null; }`,
      '',
    ].join('\n'));
    return out;
  }

  writeFileSync(out, [
    `// GENERATED by scripts/build-cli.ts — embedded node-pty natives for ${bunTarget}.`,
    `import ptyAsset from ${JSON.stringify(files.pty)} with { type: 'file' };`,
    ...(files.helper ? [`import helperAsset from ${JSON.stringify(files.helper)} with { type: 'file' };`] : []),
    `import { extractPtyAssets } from ${JSON.stringify(extract)};`,
    `export type { PtyAssets } from ${JSON.stringify(extract)};`,
    `export async function resolvePtyAssets() {`,
    `  return extractPtyAssets([`,
    `    { asset: ptyAsset, name: 'pty.node' },`,
    ...(files.helper ? [`    { asset: helperAsset, name: 'spawn-helper', exec: true },`] : []),
    `  ]);`,
    `}`,
    '',
  ].join('\n'));
  return out;
}

const ptyAssetsModule = generatePtyAssetsModule(target ?? hostBunTarget());

const result = await Bun.build({
  entrypoints: [resolve(import.meta.dir, '../src/bin.ts')],
  compile: target ? { outfile, target: target as any } : { outfile },
  plugins: [
    {
      name: 'stub-react-devtools',
      setup(build) {
        build.onResolve({ filter: /^react-devtools-core$/ }, () => ({ path: STUB }));
      },
    },
    {
      name: 'embed-pty-assets',
      setup(build) {
        build.onResolve({ filter: /pty-assets(\.ts)?$/ }, (args) => {
          const full = resolve(args.importer ? resolve(args.importer, '..') : ROOT, args.path);
          if (full === PTY_ASSETS_SRC) return { path: ptyAssetsModule };
          return undefined;
        });
      },
    },
  ],
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

console.log(`✓ compiled ${outfile}${target ? ` (${target})` : ''}`);
